// Client-safe constants: the settings form is a client component, so these can't
// live in lib/closures.ts — that module pulls in better-sqlite3 through lib/db.
//
// Emoji are plain text, not assets: no registry, no bundle cost, nothing to download.
// A few hundred cost the same as a few. Kept to long-established characters so they
// don't render as empty boxes on older systems; the picker also takes anything else
// through the operating system's own emoji keyboard.
//
// `kw` are Czech search keywords — without them the search box has nothing to match,
// since an emoji carries no readable name of its own.
export const DEFAULT_CLOSURE_ICON = "🚫";

export interface ClosureIcon {
  char: string;
  kw: string;
}

export const CLOSURE_ICON_GROUPS: { label: string; icons: ClosureIcon[] }[] = [
  {
    label: "Zavřeno",
    icons: [
      { char: "🚫", kw: "zákaz zavřeno stop nic" },
      { char: "⛔", kw: "zákaz vstupu zavřeno stop" },
      { char: "❌", kw: "křížek ne zrušeno" },
      { char: "🔒", kw: "zámek zamčeno zavřeno" },
      { char: "🔐", kw: "zámek klíč zabezpečeno" },
      { char: "🚷", kw: "zákaz chodců zavřeno" },
      { char: "🛑", kw: "stopka stop zastavit" },
      { char: "⚠️", kw: "pozor varování výstraha" },
      { char: "📅", kw: "kalendář datum termín" },
      { char: "📆", kw: "kalendář datum den" },
      { char: "🗓️", kw: "kalendář plán měsíc" },
      { char: "⏰", kw: "budík čas hodiny" },
      { char: "⏳", kw: "přesýpací hodiny čekání čas" },
      { char: "🕗", kw: "hodiny čas osm" },
      { char: "🍽️", kw: "talíř příbor jídlo oběd" },
      { char: "🚱", kw: "nepitná voda zákaz" },
      { char: "💤", kw: "spánek pauza klid" },
      { char: "🌙", kw: "měsíc noc zavřeno" },
      { char: "🔕", kw: "ztlumeno zvonek ticho" },
      { char: "📵", kw: "zákaz telefonu ticho" },
    ],
  },
  {
    label: "Dovolená a cesty",
    icons: [
      { char: "🏖️", kw: "pláž dovolená slunečník moře" },
      { char: "⛱️", kw: "slunečník pláž dovolená" },
      { char: "🌴", kw: "palma tropy dovolená" },
      { char: "🌞", kw: "slunce léto teplo" },
      { char: "😎", kw: "brýle pohoda dovolená" },
      { char: "🕶️", kw: "sluneční brýle léto" },
      { char: "🧳", kw: "kufr zavazadlo cesta" },
      { char: "✈️", kw: "letadlo let dovolená cesta" },
      { char: "🛫", kw: "vzlet letadlo odlet" },
      { char: "🚗", kw: "auto cesta výlet" },
      { char: "🚐", kw: "dodávka výlet karavan" },
      { char: "🚂", kw: "vlak cesta výlet" },
      { char: "🚢", kw: "loď plavba dovolená" },
      { char: "⛵", kw: "plachetnice loď moře" },
      { char: "🏝️", kw: "ostrov tropy dovolená" },
      { char: "🏕️", kw: "kemp stan příroda" },
      { char: "⛺", kw: "stan kemp tábor" },
      { char: "🎒", kw: "batoh výlet turistika" },
      { char: "🗺️", kw: "mapa cesta výlet" },
      { char: "🧭", kw: "kompas cesta orientace" },
      { char: "📸", kw: "foto fotoaparát dovolená" },
      { char: "🏊", kw: "plavání bazén léto" },
      { char: "🚴", kw: "kolo cyklistika výlet" },
      { char: "⛰️", kw: "hory příroda výlet" },
      { char: "🏔️", kw: "hory sníh vrchol" },
      { char: "🎿", kw: "lyže zima hory" },
      { char: "🏂", kw: "snowboard zima hory" },
      { char: "🍹", kw: "drink koktejl dovolená" },
      { char: "🐚", kw: "mušle pláž moře" },
      { char: "🦩", kw: "plameňák tropy dovolená" },
    ],
  },
  {
    label: "Svátky",
    icons: [
      { char: "🎄", kw: "vánoce stromek prosinec" },
      { char: "🎅", kw: "santa vánoce ježíšek" },
      { char: "🤶", kw: "vánoce santa babička" },
      { char: "🎁", kw: "dárek vánoce nadílka" },
      { char: "🔔", kw: "zvonek vánoce" },
      { char: "🕯️", kw: "svíčka advent památka" },
      { char: "✨", kw: "jiskry svátek oslava" },
      { char: "🎆", kw: "ohňostroj silvestr nový rok" },
      { char: "🎇", kw: "prskavka silvestr oslava" },
      { char: "🥂", kw: "přípitek oslava silvestr" },
      { char: "🍾", kw: "šampaňské oslava nový rok" },
      { char: "🎊", kw: "konfety oslava" },
      { char: "🎉", kw: "oslava párty svátek" },
      { char: "🐣", kw: "velikonoce kuře jaro" },
      { char: "🐰", kw: "velikonoce zajíc jaro" },
      { char: "🥚", kw: "vajíčko velikonoce" },
      { char: "🌷", kw: "tulipán jaro květina" },
      { char: "💐", kw: "kytice svátek oslava" },
      { char: "❤️", kw: "srdce valentýn láska" },
      { char: "🎃", kw: "dýně halloween podzim" },
      { char: "🦃", kw: "krocan svátek hostina" },
      { char: "🇨🇿", kw: "česko státní svátek vlajka" },
      { char: "🏅", kw: "medaile výročí ocenění" },
      { char: "🎂", kw: "dort narozeniny oslava" },
      { char: "🎈", kw: "balónek oslava párty" },
    ],
  },
  {
    label: "Počasí a období",
    icons: [
      { char: "☀️", kw: "slunce jasno léto horko" },
      { char: "🌤️", kw: "skoro jasno slunce mrak" },
      { char: "⛅", kw: "polojasno mrak slunce" },
      { char: "☁️", kw: "mrak oblačno zataženo" },
      { char: "🌧️", kw: "déšť prší mokro" },
      { char: "⛈️", kw: "bouřka déšť blesk" },
      { char: "🌩️", kw: "blesk bouřka" },
      { char: "🌨️", kw: "sněžení sníh zima" },
      { char: "❄️", kw: "sníh vločka zima mráz" },
      { char: "☃️", kw: "sněhulák zima sníh" },
      { char: "⛄", kw: "sněhulák zima" },
      { char: "🌬️", kw: "vítr vichřice" },
      { char: "🌪️", kw: "tornádo vichřice bouře" },
      { char: "🌡️", kw: "teploměr teplota horko" },
      { char: "🔥", kw: "oheň požár horko" },
      { char: "💧", kw: "voda kapka vlhko" },
      { char: "🌊", kw: "vlna voda povodeň" },
      { char: "🍂", kw: "listí podzim" },
      { char: "🍁", kw: "list podzim javor" },
      { char: "🌱", kw: "klíček jaro růst" },
      { char: "🌸", kw: "květ jaro sakura" },
      { char: "🌻", kw: "slunečnice léto" },
      { char: "🌰", kw: "kaštan podzim" },
    ],
  },
  {
    label: "Údržba a práce",
    icons: [
      { char: "🔧", kw: "klíč oprava údržba montáž" },
      { char: "🔨", kw: "kladivo oprava stavba" },
      { char: "⚒️", kw: "nářadí oprava dílna" },
      { char: "🛠️", kw: "nářadí údržba servis" },
      { char: "🪛", kw: "šroubovák oprava montáž" },
      { char: "🔩", kw: "šroub matice montáž" },
      { char: "⚙️", kw: "ozubené kolo servis technika" },
      { char: "🧰", kw: "bedna nářadí servis" },
      { char: "🪜", kw: "žebřík oprava malování" },
      { char: "🧱", kw: "cihly zeď stavba" },
      { char: "🚧", kw: "uzavírka stavba rekonstrukce" },
      { char: "🏗️", kw: "jeřáb stavba rekonstrukce" },
      { char: "👷", kw: "dělník stavba rekonstrukce" },
      { char: "🎨", kw: "malování barvy výmalba" },
      { char: "🖌️", kw: "štětec malování výmalba" },
      { char: "🧹", kw: "koště úklid sanitární" },
      { char: "🧽", kw: "houba úklid mytí" },
      { char: "🧼", kw: "mýdlo úklid hygiena" },
      { char: "🪣", kw: "kbelík úklid mytí" },
      { char: "🚿", kw: "sprcha voda mytí" },
      { char: "🔌", kw: "zásuvka elektřina proud" },
      { char: "💡", kw: "žárovka světlo elektřina" },
      { char: "🔋", kw: "baterie energie" },
      { char: "🖥️", kw: "počítač systém technika" },
      { char: "🏭", kw: "továrna provoz výroba" },
      { char: "📦", kw: "krabice dodávka sklad" },
      { char: "🚚", kw: "dodávka rozvoz doprava" },
      { char: "📋", kw: "seznam plán úkoly" },
      { char: "📝", kw: "poznámka zápis" },
      { char: "✅", kw: "hotovo splněno ok" },
    ],
  },
  {
    label: "Zdraví a nouze",
    icons: [
      { char: "🤒", kw: "nemoc horečka chřipka" },
      { char: "🤧", kw: "kýchání nemoc rýma" },
      { char: "😷", kw: "rouška nemoc karanténa" },
      { char: "🏥", kw: "nemocnice zdraví" },
      { char: "🚑", kw: "sanitka záchranka nehoda" },
      { char: "💊", kw: "léky nemoc" },
      { char: "💉", kw: "injekce očkování" },
      { char: "🩹", kw: "náplast úraz" },
      { char: "🧪", kw: "zkumavka hygiena test" },
      { char: "☣️", kw: "biohazard nákaza hygiena" },
      { char: "⚡", kw: "elektřina výpadek proud" },
      { char: "🔥", kw: "požár oheň havárie" },
      { char: "🚒", kw: "hasiči požár" },
      { char: "🧯", kw: "hasicí přístroj požár" },
      { char: "🆘", kw: "nouze pomoc havárie" },
      { char: "📢", kw: "hlášení oznámení výstraha" },
      { char: "🔦", kw: "baterka výpadek proudu" },
      { char: "🩺", kw: "lékař zdraví prohlídka" },
    ],
  },
  {
    label: "Jídlo a pití",
    icons: [
      { char: "🍽️", kw: "talíř oběd jídlo" },
      { char: "🍲", kw: "polévka hrnec jídlo" },
      { char: "🥣", kw: "miska polévka" },
      { char: "🍜", kw: "nudle polévka" },
      { char: "🍝", kw: "špagety těstoviny" },
      { char: "🍛", kw: "rýže omáčka jídlo" },
      { char: "🥘", kw: "pánev jídlo guláš" },
      { char: "🍖", kw: "maso pečeně" },
      { char: "🍗", kw: "kuře stehno maso" },
      { char: "🥩", kw: "steak maso" },
      { char: "🍞", kw: "chleba pečivo" },
      { char: "🥖", kw: "bageta pečivo rohlík" },
      { char: "🥔", kw: "brambory příloha" },
      { char: "🥕", kw: "mrkev zelenina" },
      { char: "🥦", kw: "brokolice zelenina" },
      { char: "🧅", kw: "cibule zelenina" },
      { char: "🍅", kw: "rajče zelenina" },
      { char: "🧀", kw: "sýr" },
      { char: "🍰", kw: "dort zákusek sladké" },
      { char: "🥧", kw: "koláč moučník" },
      { char: "🍮", kw: "pudink dezert" },
      { char: "☕", kw: "káva nápoj" },
      { char: "🍵", kw: "čaj nápoj" },
      { char: "🥤", kw: "nápoj limonáda" },
      { char: "🍺", kw: "pivo nápoj" },
      { char: "👨‍🍳", kw: "kuchař kuchyně vaření" },
      { char: "🔪", kw: "nůž kuchyně příprava" },
      { char: "🥄", kw: "lžíce jídlo" },
      { char: "🧂", kw: "sůl koření" },
    ],
  },
  {
    label: "Ostatní",
    icons: [
      { char: "ℹ️", kw: "informace info" },
      { char: "❗", kw: "vykřičník důležité pozor" },
      { char: "❓", kw: "otazník dotaz" },
      { char: "💬", kw: "zpráva komentář" },
      { char: "📣", kw: "megafon oznámení" },
      { char: "🏢", kw: "budova firma kancelář" },
      { char: "🏠", kw: "dům domov" },
      { char: "🔑", kw: "klíč přístup" },
      { char: "💰", kw: "peníze platba" },
      { char: "💸", kw: "peníze výdaj platba" },
      { char: "📊", kw: "graf statistika" },
      { char: "🎯", kw: "terč cíl" },
      { char: "🧾", kw: "účtenka faktura" },
      { char: "📌", kw: "připínáček důležité" },
      { char: "⭐", kw: "hvězda oblíbené" },
      { char: "🌟", kw: "hvězda výjimečné" },
      { char: "🙂", kw: "úsměv smajlík" },
      { char: "😴", kw: "spánek pauza klid" },
      { char: "🤷", kw: "nevím pokrčení" },
      { char: "👍", kw: "palec ok souhlas" },
      { char: "👋", kw: "ahoj pozdrav" },
      { char: "🤝", kw: "dohoda podání ruky" },
      { char: "🐶", kw: "pes zvíře" },
      { char: "🐱", kw: "kočka zvíře" },
      { char: "🦆", kw: "kachna zvíře" },
    ],
  },
];

export const CLOSURE_ICON_COUNT = CLOSURE_ICON_GROUPS.reduce((n, g) => n + g.icons.length, 0);

// Flat list for search — the picker matches keywords across every category at once.
export const ALL_CLOSURE_ICONS: ClosureIcon[] = CLOSURE_ICON_GROUPS.flatMap((g) =>
  g.icons.map((i) => ({ ...i, kw: `${i.kw} ${g.label.toLowerCase()}` }))
);
