import type { IconData } from "@gravity-ui/uikit";
import {
  Alarm,
  AlarmFill,
  AntennaSignal,
  ArrowDownToLine,
  ArrowLeft,
  ArrowsRotateRight,
  Bell,
  BellDot,
  BellFill,
  Book,
  BookOpen,
  Calendar,
  CalendarXmark,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleCheckFill,
  CircleInfo,
  CircleInfoFill,
  CircleQuestion,
  CircleRuble,
  CircleXmark,
  CircleXmarkFill,
  Clock,
  ClockArrowRotateLeft,
  ClockFill,
  Code,
  Cup,
  EllipsisVertical,
  Envelope,
  FaceRobot,
  FileArrowUp,
  FileLetterP,
  FileText,
  Gear,
  House,
  HouseFill,
  Keyboard,
  Link,
  Lock,
  LockFill,
  LockOpen,
  LockOpenFill,
  PaperPlane,
  Pencil,
  Person,
  Persons,
  Plus,
  Receipt,
  ShoppingBasket,
  Stopwatch,
  Sun,
  Terminal,
  TrashBin,
  TriangleExclamation,
  TriangleExclamationFill,
  Wrench,
  Xmark,
} from "@gravity-ui/icons";

type IconPair = { outline: IconData; filled?: IconData };

/** Legacy Material icon names → Gravity UI icon data */
export const GRAVITY_ICON_MAP: Record<string, IconPair> = {
  add: { outline: Plus },
  alarm: { outline: Alarm, filled: AlarmFill },
  arrow_back: { outline: ArrowLeft },
  assignment: { outline: FileText },
  build: { outline: Wrench },
  calendar_today: { outline: Calendar },
  check: { outline: Check },
  check_circle: { outline: CircleCheck, filled: CircleCheckFill },
  chevron_right: { outline: ChevronRight },
  close: { outline: Xmark },
  delete: { outline: TrashBin },
  download: { outline: ArrowDownToLine },
  edit: { outline: Pencil },
  error: { outline: CircleXmark, filled: CircleXmarkFill },
  event_busy: { outline: CalendarXmark },
  event_upcoming: { outline: Calendar },
  expand_less: { outline: ChevronUp },
  expand_more: { outline: ChevronDown },
  group: { outline: Person },
  groups: { outline: Persons },
  help_outline: { outline: CircleQuestion },
  history: { outline: ClockArrowRotateLeft },
  home_work: { outline: House, filled: HouseFill },
  info: { outline: CircleInfo, filled: CircleInfoFill },
  integration_instructions: { outline: Code },
  keyboard: { outline: Keyboard },
  link: { outline: Link },
  local_pizza: { outline: Cup },
  lock: { outline: Lock, filled: LockFill },
  lock_open: { outline: LockOpen, filled: LockOpenFill },
  lunch_dining: { outline: ShoppingBasket },
  mail: { outline: Envelope },
  manage_history: { outline: ClockArrowRotateLeft },
  menu_book: { outline: Book },
  more_vert: { outline: EllipsisVertical },
  no_meals: { outline: CalendarXmark },
  notifications: { outline: Bell },
  notifications_active: { outline: BellDot, filled: BellFill },
  payments: { outline: CircleRuble },
  picture_as_pdf: { outline: FileLetterP },
  receipt_long: { outline: Receipt },
  refresh: { outline: ArrowsRotateRight },
  restaurant: { outline: Cup },
  restaurant_menu: { outline: BookOpen },
  schedule: { outline: Clock, filled: ClockFill },
  send: { outline: PaperPlane },
  settings: { outline: Gear },
  shopping_basket: { outline: ShoppingBasket },
  smart_toy: { outline: FaceRobot },
  terminal: { outline: Terminal },
  timer: { outline: Stopwatch },
  upload_file: { outline: FileArrowUp },
  warning: { outline: TriangleExclamation, filled: TriangleExclamationFill },
  wb_sunny: { outline: Sun },
  wifi_off: { outline: AntennaSignal },
};

export function resolveGravityIcon(name: string, fill = false): IconData | null {
  const pair = GRAVITY_ICON_MAP[name];
  if (!pair) return null;
  if (fill && pair.filled) return pair.filled;
  return pair.outline;
}
